version: '3.8'

services:
  fingmap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fingmap
    ports:
      - "8123:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
